### ISSUE TITLE
rdf_term/1 vs rdf_node/1

### ISSUE THREAD

**Issue by JanWielemaker** [JanWielemaker/rdf11#1]
What is the intended difference?

**Comment by wouterbeek** [comment]
* Nodes = the intersection of subject and object terms.
  * Terms = the intersection of blank nodes, IRIs, and literals.

Specifically, IRIs that only appear in the predicate position should not be considered nodes, as they are more similar to graph-theoretic edges.

**Comment by JanWielemaker** [comment]
Thanks.  I assume you mean _union_ rather than _intersection_ ...

**Comment by wouterbeek** [comment]
@JanWielemaker Indeed! Fixed that.

**Comment by JanWielemaker** [comment]
Ok, typos aside, I think e7f413088cd5fae1742532c2d74bf8a49d34f140 gets these predicates right.
