### ISSUE TITLE
Querying with uninstantiated datatype IRI buggy

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/rdf11#14]
Querying with uninstantiated datatype IRI returns back every datatype IRI currently asserted.

Reproducible example:
```prolog
?- rdf_assert(a, b, true).
?- rdf(a, b, 1^^D).
D = 'http://www.w3.org/2001/XMLSchema#boolean'.
```

**Comment by wouterbeek** [comment]
I have a better reproducible case now:

```prolog
?- rdf_assert(x, x, "x"^^x, x).
?- rdf_assert(y, y, "y"^^y, y).
?- rdf(S, P, "x"^^D, G).
S = P, P = D, D = G, G = x ;
S = P, P = D, D = G, G = y.
```

**Comment by JanWielemaker** [comment]
Pushed a fix to semweb.  Note this repository plays no role anymore.  Maybe I should delete it, or is there
something here we want to preserve?

**Comment by wouterbeek** [comment]
@JanWielemaker There are still some open issues and Wikis in this repo, so I want to maintain it for say a month.  I will look into the issues in the meantime and merge all useful stuff over to Semweb.

**Comment by wouterbeek** [comment]
The recent fix is not sufficient to solve this.  Reproducible example:

```prolog
?- rdf_assert(x, x, "x"^^x, x).
?- rdf(S, P, "x"^^D, G).
false.
```

The problem is that with uninstantiated datatype IRI we do not know the conversion that has to be applied to the `rdf11`-conform value in order to end up with the `rdf_db`-conform value.  I do not see a better solution then the following cumbersome procedure:

For calls of the form `rdf(S, P, V^^D, G)` where value `V` is instantiated and datatype IRI `D` is not:

1. Call `rdf(S, P, O, G)`
2. For each instantiation of `O` interpret the lexical form based on the datatype IRI, resulting in value `V'`.
3. Compare the interpreted value with the given value, i.e., `V' == V`.

This also means that querying for values independently of their datatype IRIs should be discouraged since it is inherently slow.

**Comment by JanWielemaker** [comment]
That was my first impression as well, but it is not as bad.  The reason is that only numerical values really use multiple lexical representations for the same value.  So, if the input value cannot be interpreted as a number, we can do lexical matching.  Your test failed due to an implementation error in the previous patch.  Fixed and added two more test cases.  Trying to close again :)

**Comment by wouterbeek** [comment]
@JanWielemaker Thanks!
