### ISSUE TITLE
Review our strategy for IRI prefix expansion

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/rdf11#19]
# Predicates

  - `rdf_equal/2` expands IRIs at compile-time
  - `rdf_global_id/2` expands IRIs at run-time
  - `rdf_global_object/2` expands IRIs and literals at run-time
  - `rdf_global_term/2` expands compound terms at run-time

# Declarations

  - `rdf_meta/1`

How does it interact with `meta_predicate/1` and `html_meta/1`?

# Contexts in which prefix notation does not work

  - Predicates from `library(aggregate)`
  - Predicates from `library(apply)`

**Comment by JanWielemaker** [comment]
rdf_meta expansion works fine for these libraries, but you must ensure they are loaded into the current context to make the meta-predicate definitions available.
