### ISSUE TITLE
Float parsing, canonical serialization

### ISSUE THREAD

**Issue by JanWielemaker** [JanWielemaker/rdf11#2]
XSD floats are not the same as Prolog:

  - May end in `.`
  - Prolog has no `NaN` and +/- infinity

**Comment by wouterbeek** [comment]
There is also a distinction in the canonical representation. XSD 1.1 always uses exponent notation (with capital `E`).  See http://www.w3.org/TR/xmlschema11-2/#f-unsSciCanFragMap
