### ISSUE TITLE
Enumerate/check bnode|iri?

### ISSUE THREAD

**Issue by JanWielemaker** [JanWielemaker/rdf11#4]
We have rdf_iri/1, rdf_bnode/1, rdf_literal/1.   All great, but the notion of the union of IRIs and BNodes is quite useful as that is the type that may appear in intermediate nodes.  What is the right name for that predicate?

**Comment by wouterbeek** [comment]
`rdf_nonliteral/1`?

**Comment by wouterbeek** [comment]
Are we leaving this enumerator predicate out?  BTW, why would it be useful to know what would qualify as a node term if we already know what does qualify as a node term, i.e., `rdf_node/1`)?

**Comment by wouterbeek** [comment]
`rdf_node/1` is sufficient IMO.  It does not enumerate IRIs that only appear in the predicate position and it enumerates literals, but `rdf_node(X), \+ rdf_is_literal(X)` is almost `rdf_nonliteral(X)`.
