### ISSUE TITLE
Language-tagged string operator @ conflicts with library chr

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/rdf11#8]
Loading the following program:
```prolog
:- use_module(library(chr)).
:- use_module(library(rdf11/rdf11)).
:- chr_constraint leq/2.
label @ leq(X, Y) \ leq(X, Y) <=> true.
```

gives:
```
================================================================================
CHR compiler ERROR: invalid syntax "idempotence@leq(_G20253,_G20254)".
    `--> Undeclared constraint _G20259/_G20260 in head of rule number 1 (line 7).
	Constraint should be one of [leq/2].
================================================================================
```

The use of `@` for label annotations in CHR is an established practice.  Any way around this?

**Comment by JanWielemaker** [comment]
I'm afraid there is not much we can do.   CHR requires @ as a high-priority operator and RDF as a low-priority one.   I don't think this is serious enough to change our `string@lang`.  Depending on the order in which you include the libraries, you'll have to use @(_,_) for the other usage.

We could add e.g. `@@` as a synonym for the label operator for CHR.

**Comment by wouterbeek** [comment]
Yes the `@@`-solution would be nice!  We have to improve RDF support for CHR anyway (prefix expansion, interaction between constraint store and RDF DB) so the alternative prefix may be a part of that support module?  (I want to use CHR to calculate the OWL materialization.)

**Comment by JanWielemaker** [comment]
At least in theory, you can provide a new module that defines RDF and CHR friendly syntax and uses term-expansion to generate proper CHR and/or Prolog.

**Comment by wouterbeek** [comment]
This was moved to package semweb.
